[package]
name = "nxc-reporting"
version.workspace = true
edition.workspace = true
description = "NetExec-RS — Reporting Crate"
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
nxc-targets = { path = "../targets" }
anyhow = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
csv = { workspace = true }
uuid = { workspace = true }
