name: Publish Release

on:
  push:
    tags:
      - 'v*'  # Push events to matching v*, i.e. v1.0, v20.15.10
  workflow_dispatch:

jobs:
  build_release:
    name: Build release on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            artifact_name: nxc
            asset_name: nxc-linux-amd64
          - os: macos-latest
            artifact_name: nxc
            asset_name: nxc-macos-amd64
          - os: windows-latest
            artifact_name: nxc.exe
            asset_name: nxc-windows-amd64.exe

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      with:
        persist-credentials: false

    - name: Set up Rust
      uses: actions-rust-lang/setup-rust-toolchain@150fca883cd4034361b621bd4e6a9d34e5143606 # v1
      with:
        toolchain: stable
        
    - name: Rust Cache
      uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32 # v2

    - name: Build Release Binary
      run: cargo build --release --workspace

    - name: Rename Binary
      shell: bash
      run: |
        mv target/release/${{ matrix.artifact_name }} target/release/${{ matrix.asset_name }}

    - name: Upload Binary to Release
      uses: softprops/action-gh-release@153bb8e04406b158c6c84fc1615b65b24149a1fe # v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: target/release/${{ matrix.asset_name }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
