name: Publish Release

on:
  push:
    tags:
      - 'v*'  # Push events to matching v*, i.e. v1.0, v20.15.10
  workflow_dispatch:

jobs:
  build_release:
    name: Build release on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            artifact_name: nxc
            asset_name: nxc-linux-amd64
          - os: macos-latest
            artifact_name: nxc
            asset_name: nxc-macos-amd64
          - os: windows-latest
            artifact_name: nxc.exe
            asset_name: nxc-windows-amd64.exe

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      with:
        persist-credentials: false

    - name: Set up Rust
      uses: actions-rust-lang/setup-rust-toolchain@2b1f5e9b395427c92ee4e3331786ca3c37afe2d7 # v1
      with:
        toolchain: stable
        
    - name: Rust Cache
      uses: Swatinem/rust-cache@400e7407cfd7a091e5fbb6afec01ec146c432b7c # v2

    - name: Install dependencies (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y libkrb5-dev

    - name: Build Release Binary
      run: cargo build --release --workspace

    - name: Build Debian Package (Linux only)
      if: matrix.os == 'ubuntu-latest'
      run: |
        cargo install cargo-deb
        cargo deb -p nxc --no-build -o target/release/nxc-rs-amd64.deb

    - name: Pre-Package Binary Rename
      shell: bash
      run: |
        mv target/release/${{ matrix.artifact_name }} target/release/${{ matrix.asset_name }}

    - name: Upload Binary to Release
      uses: softprops/action-gh-release@b4309332981a82ec1c5618f44dd2e27cc8bfbfda # v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          target/release/${{ matrix.asset_name }}
          target/release/*.deb
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
