name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
        components: rustfmt, clippy

    - name: Install System Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libssl-dev pkg-config libsasl2-dev libldap2-dev

    - name: Rust Cache
      uses: Swatinem/rust-cache@v2

    - name: Check Formatting
      run: cargo fmt --all -- --check

    - name: Security Audit
      run: |
        cargo install cargo-audit
        cargo audit

    - name: Clippy Lints
      run: cargo clippy --workspace -- -D warnings

    - name: Build Workspace
      run: cargo build --workspace --verbose

    - name: Run Tests
      run: cargo test --workspace --verbose
